### PR TITLE
fix(paths): .tsx should produce .jsx

### PR DESCRIPTION
**Pull request by alexeagle**

### CODE REVIEW

**Comment by jbedard** [comment]
Did a previous change break this or was this always an issue?

**Review by jbedard — APPROVED** [review]

**Comment by alexeagle** [comment]
Hm, given that swc always downlevels JSX syntax, maybe the existing behavior was correct to output `.js`

In https://github.com/aspect-build/rules_ts/blob/007d1ab8f168879cad4ba6b741e8c6def20aa262/ts/private/ts_lib.bzl#L204 we only do this when `preserveJsx` is enabled, but `swc` has no such feature.

**Comment by jbedard** [comment]
But the tests you added passed?

**Comment by alexeagle** [comment]
Sure, that's easy if they're the wrong tests to match the wrong implementation :)

**Comment by jbedard** [comment]
I was assuming `_calculate_js_out` determines the outputs, not declares them 😅

**Pull request closed without merging**
