### PR TITLE
chore: update to rules_js 1.15.1 and aspect_bazel_lib 1.23.3

### PR DESCRIPTION
**Pull request by gregmagolan**

### CODE REVIEW

**Comment by alexeagle** [comment]
This isn't actually necessary for anything, right? End users can upgrade rules_js independently of rules_swc, we shouldn't always need to advance the minimum version unless something is breaking.

**Comment by gregmagolan** [comment]
Its actually hard to reason about what is breaking between bazel-lib & rules_js and the other rulesets in a downstream WORKSPACE. If a user calls `rules_swc_dependencies` before `rules_js_dependencies` in their WORKSPACE and gets an older version than rules_js requires than it could break. bzlmod makes it simpler to reason about but for WORKSPACEs it is best to keep all the rules_js downstream rulesets up to date with the latest of the rules_js ecosystem.

**Comment by alexeagle** [comment]
Okay I see that failure mode, but of course the user could just use the rules_swc version prior to this one, get the older aspect_bazel_lib, and have that problem.
There's no need for us to update MODULE.bazel in these "bump" PRs, we both agree, but then it's strange for us to have different versions in the two files. There's also no need to publish to BCR if the only commits are no-op changes to the MODULE.bazel file.

I suppose we're going to slow down rules_js at this point so this will just go away, and we'll rely on bzlmod in the future so we can stop doing these bumps.

**Comment by gregmagolan** [comment]
Yeah. There are still failure modes. The advice of upgrading all aspect rule sets in a single PR should always work at least.

**Pull request merged**
