### PR TITLE
(Bug): When src is not local, basename is not fully describing the fi…

### PR DESCRIPTION
**Pull request by alexeagle**
…le name

---

### Changes are visible to end-users: yes/no

- Searched for relevant documentation and updated as needed: yes/no
- Breaking change (forces users to change their own code or config): yes/no
- Suggested release notes appear below: yes/no

### Test plan

- Covered by existing test cases
- New test cases added
- Manual testing; please provide instructions so we can reproduce:

### CODE REVIEW

**Comment by jbedard** [comment]
Can we show the issue in a test?

**Comment by alexeagle** [comment]
I'm sure we could, but we don't have anyone volunteering to do that work. I'm just trusting this engineer from trunk.io that it does solve an issue https://github.com/aspect-build/rules_swc/pull/274/commits/38764a7307fcea781b08b4ee4dfad256f1038991

**Comment by jbedard** [comment]
See all the test failures...

**Comment by jbedard** [comment]
@pat-trunk-io do you recall the issue being fixed here?

**Comment by jbedard** [comment]
replaced with https://github.com/aspect-build/rules_swc/pull/279

**Pull request closed without merging**
