### PR TITLE
refactor: no default value for source_root

### PR DESCRIPTION
**Pull request by alexeagle**
fyi @realtimetodie

### CODE REVIEW

**Comment by jbedard** [comment]
Was there a specific issue this caused?

**Comment by alexeagle** [comment]
Yeah a minor one I commented on the PR that added the line

**Comment by jbedard** [comment]
Is it worth a test though?

**Comment by alexeagle** [comment]
No it's not a testable bad behavior, it's bad user documentation. The empty string default appears in the stardoc and makes users think we will pass an empty string unless they override it, which isn't true.

**Comment by alexeagle** [comment]
oh, interesting, I did not realize that empty string is already the sentinel value for a ctx.attr.string - I thought it would be `None`

**Pull request merged**
