### PR TITLE
fix: windows CI

### PR DESCRIPTION
**Pull request by alexeagle**

### CODE REVIEW

**Comment by alexeagle** [comment]
FYI @realtimetodie I'm fighting with this, it seems like the `ctx.actions.run_shell` that we had to use as a workaround for the rust stdin handling is now causing a difference in argv quoting when we pass a JSON value to the --config-json flag.

**Comment by realtimetodie** [comment]
As far as I remember, I think we could get rid of this workaround with a small logic change upstream. The swc cli would need to parse the command line arguments first, before reading from stdin. I think it is the opposite at the moment. Something like that. I will look into this tomorrow.

**Comment by realtimetodie** [comment]
I will cut a swc cli release tonight.

**Comment by realtimetodie** [comment]
I rebased from main and tried it out locally, but Windows is complaining and I can't figure out what the error is.

**Comment by realtimetodie** [comment]
🎉

**Review by jbedard — APPROVED** [review]

**Pull request merged**
