### PR TITLE
refactor: move resolved_toolchain to the main workspace

### PR DESCRIPTION
**Pull request by alexeagle**
Similar to https://github.com/bazel-contrib/rules-template/pull/48

### CODE REVIEW

**Review by kormide — APPROVED** [review]
This lgtm, but a couple of questions.
1. Is this breaking but we're okay with it because we are still on v0?
2. Can you remind me what problem the resolved toolchain solves?

**Comment by kormide** [comment]
Oh, it was to use the toolchain in a `genrule`, right?

**Comment by alexeagle** [comment]
Yes, it's breaking, though I think we could introduce an `alias` in the old location if we care to. My guess is this is rarely used and the alias is just a bit of cruft.

Yes, exactly, the updated example here is the only way I know of that a user might reference it from code.
The target is also useful on the command-line to "just run the swc binary", so this breaking change would affect people's documentation as much as anything else.

**Comment by alexeagle** [comment]
I added the `alias` so this should be non-breaking AFAIK

**Pull request merged**
